
server:
  port: 8781

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 服务的名称
spring:
  application:
    name: order-service

# 服务的名称,配置redis
  redis:
    database: 1
    host: 192.168.0.247
    port: 6379
    password: oeasy808
    timeout: 2000ms


#自定义负载均衡策略
#这里写被调用服务名
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#feign客户端请求超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  # 开启feign支持hystrix
  hystrix:
    enabled: true

#hystrix策略配置：超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#开启所有监控端点，暴露全部信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
