server:
  port: 8771

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 服务的名称
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://192.168.0.247:9411/
  # 设置日志采样比例，默认为0.1（1%），便于测试设置为1（100%采集）
  sleuth:
    sampler:
      probability: 1