spring:
  application:
    name: config-server
#git配置
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jorge_zhong/springcloud-learning
          username: jorgezhong@163.com
          password: 5201314bba
          #默认超时5秒
          timeout: 5
          #默认分支
          default-label: master
server:
  port: 9100

#指定注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

